//
// This file was generated by the JPA Modeler
//
package jpa_exercise.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;

@Entity

public class Book extends Publication implements Serializable, SaleableItem {

    @Basic
    private String author;

    public Book() {

    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Override
    public void sellCopy(Publication p) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
